# Generated by Django 5.2.7 on 2026-01-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_operatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='operator_number',
            field=models.IntegerField(default=1),
        ),
    ]
