# Generated by Django 5.2.7 on 2026-02-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_operatorprofile_operator_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht11',
            name='chlorine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='flow_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='turbidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='water_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
